name: Build

on:
  push:
    branches: [ main ]

jobs:

  setup:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build and push the go-gst docker image
      run: make docker-build docker-push
